import { NextRequest, NextResponse } from "next/server";
import { loggedFetch, debugError, debugLog } from "@/lib/api-logger";
import { requireAuth } from "@/lib/api/auth-middleware";
import { parseApiManagerRouting, parseGlobalRoutingMeta } from "@/lib/llmProxy/parse-routing";
import type { LlmProxyDetail, LlmProxyPolicy, LlmProxyUpstream } from "@/lib/llmProxy/types";

export const dynamic = "force-dynamic";

interface ApiMgrInstanceResponse {
  id?: number | string;
  assetId?: string;
  groupId?: string;
  assetVersion?: string;
  instanceLabel?: string | null;
  endpoint?: {
    uri?: string | null;
    proxyUri?: string | null;
    type?: string;
  } | null;
  endpointUri?: string | null;
  technology?: string;
  metadata?: { source?: string; globalRouting?: unknown; [key: string]: unknown };
  /** Inbound format for LLM proxies. */
  endpointType?: string;
  /** Present when includeProxyConfiguration=true. */
  proxyConfiguration?: Record<string, unknown>;
  /** Named routes from API Manager (header rules → upstream ids). */
  routing?: unknown;
  /** Exchange asset display name ("LLM Proxy Name" in Anypoint UI). */
  exchangeAssetName?: string | null;
  apiAsset?: {
    name?: string | null;
    exchangeAssetName?: string | null;
  } | null;
}

interface UpstreamsResponse {
  upstreams?: Array<{
    id?: string | number;
    label?: string;
    uri?: string;
    /** Real API Manager response carries model/format/provider here. */
    metadata?: {
      llmConfigs?: {
        model?: string;
        format?: string;
        provider?: string;
        promptTopicIDs?: string[];
      };
    };
  }>;
}

interface PolicyEntry {
  id?: string | number;
  assetId?: string;
  groupId?: string;
  policyTemplateName?: string | null;
  template?: {
    assetId?: string;
    groupId?: string;
    assetVersion?: string;
    policyTemplateName?: string;
  };
}

/** API Manager returns `{policies:[...]}` for fullInfo=true and a bare array for fullInfo=false. */
type PoliciesResponse = { policies?: PolicyEntry[] } | PolicyEntry[];

function extractPathFromUri(uri: string | null | undefined): string | null {
  if (!uri) return null;
  try {
    const url = new URL(uri);
    return url.pathname && url.pathname !== "/" ? url.pathname : null;
  } catch {
    return null;
  }
}

/**
 * Derive `publicEndpoint` (scheme+host) from `endpointUri` and `basePath`
 * from whichever URI actually carries the path. Model-Based Routing LLM
 * proxies often expose `endpointUri = https://host/` with the real base path
 * only present on `endpoint.proxyUri = http://0.0.0.0:8081/llm-proxy-...`.
 */
function extractPublicEndpointAndBasePath(
  endpointUri: string | null | undefined,
  proxyUri: string | null | undefined
): { publicEndpoint: string | null; basePath: string | null } {
  let publicEndpoint: string | null = null;
  if (endpointUri) {
    try {
      const url = new URL(endpointUri);
      publicEndpoint = `${url.protocol}//${url.host}`;
    } catch {
      /* ignore */
    }
  }
  const basePath = extractPathFromUri(endpointUri) ?? extractPathFromUri(proxyUri);
  return { publicEndpoint, basePath };
}

function detectEndpointFormat(
  inst: ApiMgrInstanceResponse,
  upstreams: LlmProxyUpstream[]
): "openai" | "gemini" | "unknown" {
  // Prefer upstream metadata: all upstreams share the inbound format.
  for (const u of upstreams) {
    const f = u.format?.toLowerCase();
    if (f === "openai") return "openai";
    if (f === "gemini") return "gemini";
  }
  const t = String(inst.endpointType ?? "").toLowerCase();
  if (t.includes("openai")) return "openai";
  if (t.includes("gemini")) return "gemini";
  return "unknown";
}

/**
 * API Manager auto-labels like "v1.0:20853307" are not user-meaningful; the
 * Exchange `assetId` is a better default display name when no custom label
 * has been set.
 */
function isAutogeneratedLabel(label: string | null | undefined): boolean {
  if (!label) return true;
  return /^v?\d+(\.\d+)*:\d+$/i.test(label.trim());
}

function detectRoutingStrategy(
  policies: LlmProxyPolicy[],
  upstreams: LlmProxyUpstream[]
): "model-based" | "semantic" | "unknown" {
  for (const p of policies) {
    const asset = String(p.assetId ?? "").toLowerCase();
    if (asset.includes("semantic-routing")) return "semantic";
    if (asset.includes("model-based-routing")) return "model-based";
  }
  // Fallback: if any upstream has promptTopicIDs, it's semantic; otherwise, if
  // we have upstreams and no explicit semantic signal, assume model-based.
  if (upstreams.some((u) => u.promptTopicIds && u.promptTopicIds.length > 0)) {
    return "semantic";
  }
  if (upstreams.length > 0) return "model-based";
  return "unknown";
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ instanceId: string }> }
) {
  const authResult = await requireAuth(request);
  if (authResult instanceof NextResponse) return authResult;
  const { baseUrl, accessToken } = authResult;

  const { instanceId } = await context.params;
  const orgId = request.nextUrl.searchParams.get("orgId");
  const envId = request.nextUrl.searchParams.get("envId");
  debugLog(
    `[LLM-PROXY-DEBUG detail] GET instanceId=${instanceId} orgId=${orgId} envId=${envId}`
  );
  if (!orgId || !envId || !instanceId) {
    return NextResponse.json(
      { error: "orgId, envId and instanceId required" },
      { status: 400 }
    );
  }

  const authHeader = `Bearer ${accessToken}`;
  const apiBase =
    `${baseUrl}/apimanager/api/v1/organizations/${encodeURIComponent(orgId)}` +
    `/environments/${encodeURIComponent(envId)}/apis/${encodeURIComponent(instanceId)}`;

  try {
    const [instRes, upstreamsRes, policiesRes] = await Promise.all([
      loggedFetch(`${apiBase}?includeProxyConfiguration=true&includeTlsContexts=true`, {
        headers: { Authorization: authHeader },
      }),
      loggedFetch(`${apiBase}/upstreams`, { headers: { Authorization: authHeader } }),
      loggedFetch(`${apiBase}/policies?fullInfo=true`, {
        headers: { Authorization: authHeader },
      }),
    ]);

    if (!instRes.ok) {
      const text = await instRes.text();
      return NextResponse.json(
        { error: `Instance failed: ${instRes.status} ${text.slice(0, 200)}` },
        { status: instRes.status }
      );
    }

    const inst = (await instRes.json()) as ApiMgrInstanceResponse;

    // Upstreams and policies are enrichment: never fail the whole detail
    // response if their bodies can't be parsed. Callers still render the
    // proxy header, base path and credentials form even when enrichment is
    // missing.
    async function safeJson<T>(res: Response, fallback: T, label: string): Promise<T> {
      if (!res.ok) return fallback;
      try {
        return (await res.json()) as T;
      } catch (err) {
        debugError(`[LLM-PROXY/DETAIL] Failed to parse ${label} body:`, err);
        return fallback;
      }
    }

    const upstreamsBody = await safeJson<UpstreamsResponse>(upstreamsRes, {}, "upstreams");
    const policiesRaw = await safeJson<PoliciesResponse>(
      policiesRes,
      { policies: [] },
      "policies"
    );
    const policiesList: PolicyEntry[] = Array.isArray(policiesRaw)
      ? policiesRaw
      : (policiesRaw.policies ?? []);

    const policies: LlmProxyPolicy[] = policiesList.map((p) => ({
      id: p.id,
      assetId: p.assetId ?? p.template?.assetId,
      groupId: p.groupId ?? p.template?.groupId,
      policyTemplateName: p.policyTemplateName ?? p.template?.policyTemplateName ?? undefined,
    }));

    const upstreams: LlmProxyUpstream[] = (upstreamsBody.upstreams ?? []).map((u) => ({
      id: u.id != null ? String(u.id) : undefined,
      label: u.label,
      uri: u.uri,
      targetModel: u.metadata?.llmConfigs?.model,
      format: u.metadata?.llmConfigs?.format,
      provider: u.metadata?.llmConfigs?.provider,
      promptTopicIds: u.metadata?.llmConfigs?.promptTopicIDs,
    }));

    const globalMeta = parseGlobalRoutingMeta(inst.metadata);
    const routesFromApi = parseApiManagerRouting(inst.routing);

    const endpointUri = inst.endpoint?.uri ?? inst.endpointUri ?? null;
    const proxyUri = inst.endpoint?.proxyUri ?? null;
    const { publicEndpoint, basePath } = extractPublicEndpointAndBasePath(endpointUri, proxyUri);
    debugLog(
      `[LLM-PROXY-DEBUG detail] resolved instanceId=${instanceId} ` +
        `endpointUri=${endpointUri} proxyUri=${proxyUri} ` +
        `-> publicEndpoint=${publicEndpoint} basePath=${basePath}`
    );

    const meaningfulLabel =
      inst.instanceLabel && !isAutogeneratedLabel(inst.instanceLabel)
        ? inst.instanceLabel
        : null;
    const exchangeName =
      inst.exchangeAssetName ||
      inst.apiAsset?.exchangeAssetName ||
      inst.apiAsset?.name ||
      null;

    const policyStrategy = detectRoutingStrategy(policies, upstreams);
    const routingStrategy =
      policyStrategy !== "unknown" ? policyStrategy : globalMeta.routingStrategy;

    const detail: LlmProxyDetail = {
      id: String(inst.id ?? instanceId),
      name:
        exchangeName ||
        meaningfulLabel ||
        inst.assetId ||
        inst.instanceLabel ||
        String(inst.id ?? instanceId),
      assetId: inst.assetId ?? "",
      groupId: inst.groupId ?? "",
      assetVersion: inst.assetVersion ?? "",
      publicEndpoint,
      basePath,
      endpointFormat: detectEndpointFormat(inst, upstreams),
      upstreams,
      policies,
      routingStrategy,
      routes: routesFromApi,
      fallbackRoute: globalMeta.fallbackRoute,
      fallbackModel: globalMeta.fallbackModel,
      fallbackThreshold: globalMeta.fallbackThreshold,
      denyTopicIds:
        globalMeta.denyTopicIds.length > 0 ? globalMeta.denyTopicIds : undefined,
    };

    debugLog(
      `[LLM-PROXY-DEBUG detail] response instanceId=${detail.id} name="${detail.name}" ` +
        `publicEndpoint=${detail.publicEndpoint} basePath=${detail.basePath} ` +
        `routingStrategy=${detail.routingStrategy}`
    );
    return NextResponse.json(detail);
  } catch (error) {
    debugError("[LLM-PROXY/DETAIL] Fetch error:", error);
    return NextResponse.json(
      { error: "Failed to load LLM Proxy detail" },
      { status: 500 }
    );
  }
}
