import { NextRequest, NextResponse } from "next/server";
import { loggedFetch, debugError, debugLog } from "@/lib/api-logger";
import { requireAuth } from "@/lib/api/auth-middleware";
import { parseApiManagerRouting, parseGlobalRoutingMeta } from "@/lib/llmProxy/parse-routing";
import type { LlmProxyListItem, LlmProxyListResponse } from "@/lib/llmProxy/types";

export const dynamic = "force-dynamic";

/**
 * Shape returned by apimanager/api/v1/.../apis (the documented, scope-compatible
 * list endpoint). Response groups API instances ("apis") under parent Exchange
 * "assets".
 */
interface ApiV1Instance {
  id?: number | string;
  assetId?: string;
  groupId?: string;
  assetVersion?: string;
  productVersion?: string;
  instanceLabel?: string | null;
  endpointUri?: string | null;
  /** e.g. `flexGateway` for Flex LLM Proxy (when API Manager includes it on list). */
  technology?: string | null;
  /** Top-level field on the list response (e.g. "llm", "raml", "mcp", "a2a"). */
  endpointType?: string | null;
  endpoint?: {
    uri?: string | null;
    proxyUri?: string | null;
    type?: string;
    apiGatewayVersion?: string;
    isCloudHub?: boolean | null;
  } | null;
  deployment?: {
    apiId?: number | string;
    environmentId?: string;
    deploymentStatus?: string;
    type?: string;
  } | null;
  autodiscoveryInstanceName?: string;
  /** Present on semantic Flex LLM Proxies when API returns it on the list response. */
  semanticServiceConfigId?: string | null;
  /**
   * Flex LLM Proxy routes (header/model rules → upstreams). Present when
   * `fullInfo=true` on the list API (see llm-proxy-api-manager-assets-reference.json).
   */
  routing?: unknown;
  /**
   * API Manager metadata. Flex Gateway LLM Proxy instances include
   * `globalRouting.llmConfigs` (routing policy). Other `endpointType: llm`
   * APIs (e.g. agent egress) use different shapes (`connectionId`, etc.).
   */
  metadata?: {
    globalRouting?: { llmConfigs?: unknown };
    protectionDirection?: string;
    connectionId?: string;
    [key: string]: unknown;
  } | null;
  /**
   * Exchange asset display name (what the Anypoint UI shows under
   * "LLM Proxy Name"). Populated on both the instance and, depending on the
   * API Manager version, nested under `apiAsset`.
   */
  exchangeAssetName?: string | null;
  apiAsset?: {
    name?: string | null;
    exchangeAssetName?: string | null;
    assetId?: string | null;
    groupId?: string | null;
  } | null;
}

interface ApiV1Asset {
  groupId?: string;
  assetId?: string;
  /** Exchange asset display name (shown as "LLM Proxy Name" in Anypoint). */
  exchangeAssetName?: string | null;
  name?: string | null;
  apis?: ApiV1Instance[];
}

interface ApiV1ListResponse {
  total?: number;
  /** New shape. */
  assets?: ApiV1Asset[];
  /** Some older variants return instances directly. */
  instances?: ApiV1Instance[];
}

/**
 * Best-effort base path extraction. Prefer the public `endpointUri` path,
 * but some proxies (observed on Model-Based Routing LLM proxies) set
 * `endpointUri` to just the host with a `/` path and keep the real base
 * path only on `endpoint.proxyUri` (e.g. `http://0.0.0.0:8081/llm-proxy-...`).
 */
function extractPathFromUri(uri: string | null | undefined): string | null {
  if (!uri) return null;
  try {
    const url = new URL(uri);
    return url.pathname && url.pathname !== "/" ? url.pathname : null;
  } catch {
    return null;
  }
}

function extractBasePath(
  endpointUri: string | null | undefined,
  proxyUri: string | null | undefined
): string | null {
  return extractPathFromUri(endpointUri) ?? extractPathFromUri(proxyUri);
}

/**
 * API Manager synthesizes labels like "v1.0:20853307" (i.e. `{assetVersion}:{id}`)
 * when no custom instance label is set. These are not user-meaningful, so we
 * skip them in favor of the Exchange assetId.
 */
function isAutogeneratedLabel(label: string | null | undefined): boolean {
  if (!label) return true;
  return /^v?\d+(\.\d+)*:\d+$/i.test(label.trim());
}

function normalize(inst: ApiV1Instance, parent?: ApiV1Asset): LlmProxyListItem {
  const endpointUri = inst.endpoint?.uri ?? inst.endpointUri ?? null;
  const proxyUri = inst.endpoint?.proxyUri ?? null;
  const groupId = inst.groupId ?? parent?.groupId ?? inst.apiAsset?.groupId ?? "";
  const assetId = inst.assetId ?? parent?.assetId ?? inst.apiAsset?.assetId ?? "";
  const exchangeName =
    inst.exchangeAssetName ||
    inst.apiAsset?.exchangeAssetName ||
    inst.apiAsset?.name ||
    parent?.exchangeAssetName ||
    parent?.name ||
    null;
  const meaningfulLabel =
    inst.instanceLabel && !isAutogeneratedLabel(inst.instanceLabel)
      ? inst.instanceLabel
      : null;
  const basePath = extractBasePath(endpointUri, proxyUri);
  const id = String(inst.id ?? "");
  const globalMeta = parseGlobalRoutingMeta(inst.metadata);
  const routes = parseApiManagerRouting(inst.routing);
  debugLog(
    `[LLM-PROXY-DEBUG list.normalize] id=${id} assetId=${assetId} ` +
      `endpointUri=${endpointUri} proxyUri=${proxyUri} ` +
      `resolvedBasePath=${basePath}`
  );
  return {
    id,
    assetId,
    name:
      exchangeName ||
      meaningfulLabel ||
      assetId ||
      inst.autodiscoveryInstanceName ||
      inst.instanceLabel ||
      id,
    groupId,
    assetVersion: inst.assetVersion ?? inst.productVersion ?? "",
    endpointUri,
    basePath,
    deploymentStatus: inst.deployment?.deploymentStatus ?? null,
    routingStrategy: globalMeta.routingStrategy,
    routes,
    fallbackRoute: globalMeta.fallbackRoute,
    fallbackModel: globalMeta.fallbackModel,
    fallbackThreshold: globalMeta.fallbackThreshold,
    denyTopicIds:
      globalMeta.denyTopicIds.length > 0 ? globalMeta.denyTopicIds : undefined,
  };
}

function isLlmProxy(inst: ApiV1Instance): boolean {
  const endpointType = inst.endpointType ?? inst.endpoint?.type;
  if (typeof endpointType === "string") return endpointType.toLowerCase() === "llm";
  return false;
}

/**
 * Agent egress / non-proxy LLM APIs sometimes expose `metadata.connectionId` without
 * Flex routing. Skip those so the list stays proxy-focused.
 */
function isLikelyAgentEgressLlm(inst: ApiV1Instance): boolean {
  const m = inst.metadata;
  if (!m || typeof m !== "object") return false;
  if (!("connectionId" in m) || m.connectionId == null) return false;

  const gr = m.globalRouting;
  const hasLlmConfigs =
    gr != null && typeof gr === "object" && (gr as { llmConfigs?: unknown }).llmConfigs != null;
  if (hasLlmConfigs) return false;

  const routing = inst.routing;
  if (Array.isArray(routing) && routing.length > 0) return false;

  return true;
}

/**
 * Flex Gateway **LLM Proxy** instances: prefer `metadata.globalRouting.llmConfigs` (strict).
 * Many orgs' list responses omit that block even when Anypoint shows LLM Proxies — also accept
 * non-empty `routing`, `technology` containing `flex`, or a semantic-service config id.
 */
function isFlexGatewayLlmProxyAsset(inst: ApiV1Instance, _parent?: ApiV1Asset): boolean {
  if (!isLlmProxy(inst)) return false;
  if (isLikelyAgentEgressLlm(inst)) return false;

  const gr = inst.metadata?.globalRouting;
  if (gr != null && typeof gr === "object" && gr.llmConfigs != null) return true;

  const routing = inst.routing;
  if (Array.isArray(routing) && routing.length > 0) return true;

  const tech = String(inst.technology ?? "").toLowerCase();
  if (tech.includes("flex")) return true;

  const semId = inst.semanticServiceConfigId;
  if (typeof semId === "string" && semId.trim().length > 0) return true;

  // List responses often omit `globalRouting`, `routing`, and `technology`; still `endpointType: llm`.
  // After excluding likely agent egress, include the row so real Flex proxies appear.
  return true;
}

/**
 * Keep instances that have API Manager routing rows and/or Flex `llmConfigs` (semantic/model policy).
 * Rows with neither cannot drive the proxy UI — omit them from the list.
 */
function hasRoutingOrLlmConfigs(inst: ApiV1Instance): boolean {
  const routing = inst.routing;
  if (Array.isArray(routing) && routing.length > 0) return true;

  const gr = inst.metadata?.globalRouting;
  if (gr != null && typeof gr === "object") {
    const llm = (gr as { llmConfigs?: unknown }).llmConfigs;
    if (llm != null && typeof llm === "object") return true;
  }

  return false;
}

export async function GET(request: NextRequest) {
  const authResult = await requireAuth(request);
  if (authResult instanceof NextResponse) return authResult;
  const { baseUrl, accessToken } = authResult;

  const orgId = request.nextUrl.searchParams.get("orgId");
  const envId = request.nextUrl.searchParams.get("envId");
  if (!orgId || !envId) {
    return NextResponse.json(
      { error: "orgId and envId required", total: 0, instances: [] },
      { status: 400 }
    );
  }

  // Documented API Manager list endpoint. `family=llm` limits the response to
  // LLM-based APIs; `fullInfo=true` populates the endpoint and routing details
  // needed to distinguish Flex LLM proxies from agent-egress instances.
  const url =
    `${baseUrl}/apimanager/api/v1/organizations/${encodeURIComponent(orgId)}` +
    `/environments/${encodeURIComponent(envId)}/apis` +
    `?family=llm&fullInfo=true&limit=250&offset=0&sort=name&ascending=false`;

  try {
    const res = await loggedFetch(url, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: "application/json",
      },
    });
    if (!res.ok) {
      const text = await res.text();
      debugError("[LLM-PROXY/LIST] API error:", res.status, text);
      return NextResponse.json(
        { error: `LLM Proxies list failed: ${res.status} ${text.slice(0, 200)}`, total: 0, instances: [] },
        { status: res.status }
      );
    }
    const data = (await res.json()) as ApiV1ListResponse;

    const llmInstances: LlmProxyListItem[] = [];
    if (Array.isArray(data.assets)) {
      for (const asset of data.assets) {
        if (!Array.isArray(asset.apis)) continue;
        for (const api of asset.apis) {
          if (
            isFlexGatewayLlmProxyAsset(api, asset) &&
            hasRoutingOrLlmConfigs(api)
          ) {
            llmInstances.push(normalize(api, asset));
          }
        }
      }
    } else if (Array.isArray(data.instances)) {
      for (const inst of data.instances) {
        if (isFlexGatewayLlmProxyAsset(inst) && hasRoutingOrLlmConfigs(inst)) {
          llmInstances.push(normalize(inst));
        }
      }
    }

    const body: LlmProxyListResponse = {
      total: llmInstances.length,
      instances: llmInstances,
    };
    debugLog(
      `[LLM-PROXY-DEBUG list] Returning ${body.instances.length} LLM proxies: ` +
        JSON.stringify(
          body.instances.map((i) => ({
            id: i.id,
            assetId: i.assetId,
            name: i.name,
            endpointUri: i.endpointUri,
            basePath: i.basePath,
          }))
        )
    );
    return NextResponse.json(body);
  } catch (error) {
    debugError("[LLM-PROXY/LIST] Fetch error:", error);
    return NextResponse.json(
      { error: "Failed to list LLM Proxies", total: 0, instances: [] },
      { status: 500 }
    );
  }
}
